name: Build

on:
  push:
    branches:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test ESLint
        run: npm run test:eslint

      - name: Test Markdown
        run: npm run test:markdown

      - name: Test Jest
        run: npm run test

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/master' &&
            github.repository == 'yoriiis/svg-chunk-webpack-plugin' &&
            github.event_name != 'pull_request'
        with:
          name: coverage
          path: coverage

      - name: Build
        run: |
          npm run build:tsc
          npm run build:example

  deploy-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    if: success() &&
        github.ref == 'refs/heads/master' &&
        github.repository == 'yoriiis/svg-chunk-webpack-plugin' &&
        github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v2

      - name: Download coverage artifacts
        uses: actions/download-artifact@v1
        with:
          name: coverage

      - uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
